version: '3'

services:
  caddy:
    image: caddy
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "3001:3001"
    depends_on:
      - client
    restart: always

  client:
    build:
      context: ./client
    ports:
      - "8080:3000"
    depends_on:
      - server
    restart: always

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    restart: always

volumes:
  caddy_data:
  caddy_config:
